#!/bin/bash

#xrandr --output eDP1 --dpi 168

fcitx5 &
~/.fehbg &
picom -o 0.95 -i 0.88 --detect-rounded-corners --vsync --blur-background-fixed -f -D 5 -c -b
sh ~/scripts/autostart.sh &
#picom -CGB &

xlayoutdisplay -p DP1 -o DP1 -o eDP1
#GDK_SCALE=2

GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
SDL_IM_MODULE=fcitx
